/* The generator: it writes the brand assets from the mark source
   (ADR 0036). Run it with `npm run generate:icons`. */

import { writeFileSync } from 'node:fs';
import { Resvg } from '@resvg/resvg-js';
import { fitMark, fitRun, outlineMark, outlineRun } from './mark.mjs';

const PUBLIC_DIR = new URL('../public/', import.meta.url);

const FAVICON = { size: 64, inset: 3 };

const LABEL = 'lf. — lukefredrickson.dev';

/* The favicon sits against the browser tab strip, which follows the OS
   theme and never the site toggle (ADR 0036). */
const THEMES = {
  light: { ltr: '#55516f', dot: '#e1a035' },
  dark: { ltr: '#dddceb', dot: '#ffc05a' },
};

/* Every raster brand asset draws on this square, then scales to its frame
   size. The tile, the insets, and the ICO radius come from ADR 0037. */
const TILE = { size: 64, fill: '#211d38' };

const ICO = { sizes: [16, 32], insetFraction: 0.1, radiusFraction: 0.125 };

const PNGS = [
  { name: 'apple-touch-icon.png', size: 180, insetFraction: 0.072 },
  { name: 'icon-192.png', size: 192, insetFraction: 0.154 },
  { name: 'icon-512.png', size: 512, insetFraction: 0.154 },
];

/* The OG card's palette is the dusk theme; its geometry is measured from
   the shipped card (ADR 0038). Every length is a canvas unit. */
const OG = {
  size: { width: 1200, height: 630 },
  card: { inset: 40, radius: 16, border: 1.5, fill: '#2d2945', stroke: '#55516f' },
  tile: { x: 116, y: 156.17, size: 150, inset: 12.5, radius: 10 },
  wordmark: {
    domain: 'lukefredrickson',
    tld: '.dev',
    x: 116,
    baseline: 404.1,
    size: 72,
    advanceEm: 0.56,
  },
  highlighter: { fill: '#ffc05a', opacity: 0.6, heightEm: 0.36, dropEm: 0.1665 },
  tagline: {
    text: 'building software for the energy transition',
    fill: '#8e8aac',
    x: 116,
    baseline: 464.25,
    size: 28,
    weight: 400,
    advanceEm: 0.578,
  },
};

const mark = outlineMark();

write('favicon.svg', faviconSvg(mark));

for (const { name, size, insetFraction } of PNGS) {
  write(name, frame(tileSvg(mark, { insetFraction }), size));
}

const icoSvg = tileSvg(mark, ICO);
const icoFrames = ICO.sizes.map((size) => ({ size, png: frame(icoSvg, size) }));
write('favicon.ico', ico(icoFrames));

write('og-default.png', frame(ogCardSvg(mark), OG.size.width));

function faviconSvg({ outlines, ink }) {
  const transform = fitMark(ink, FAVICON);
  const paths = outlines
    .map(({ fillClass, d }) => `<path class="${fillClass}" d="${d}"/>`)
    .join('');
  const { size } = FAVICON;

  return `${[
    '<!-- Generated by `npm run generate:icons`. Do not edit (ADR 0036). -->',
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}" role="img" aria-label="${LABEL}">`,
    `<title>${LABEL}</title>`,
    `<style>${fillRules(THEMES.light)}@media(prefers-color-scheme:dark){${fillRules(THEMES.dark)}}</style>`,
    `<g transform="${transform}">${paths}</g>`,
    '</svg>',
  ].join('\n')}\n`;
}

function fillRules(theme) {
  return Object.entries(theme)
    .map(([fillClass, fill]) => `.${fillClass}{fill:${fill}}`)
    .join('');
}

function tileSvg(mark, { insetFraction, radiusFraction = 0 }) {
  const { size } = TILE;

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">`,
    tile(mark, {
      size,
      inset: insetFraction * size,
      radius: radiusFraction * size,
    }),
    '</svg>',
  ].join('');
}

/* A raster brand asset answers no theme query, so it wears the dark
   fills (ADR 0037). */
function tile({ outlines, ink }, { size, inset, radius }) {
  const transform = fitMark(ink, { size, inset });
  const paths = outlines
    .map(({ fillClass, d }) => `<path fill="${THEMES.dark[fillClass]}" d="${d}"/>`)
    .join('');

  return [
    `<rect width="${size}" height="${size}" rx="${radius}" fill="${TILE.fill}"/>`,
    `<g transform="${transform}">${paths}</g>`,
  ].join('');
}

function ogCardSvg(mark) {
  const { size, card, tile: tileBox, wordmark, highlighter, tagline } = OG;
  const run = { weight: 700, advanceEm: wordmark.advanceEm };

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size.width} ${size.height}" width="${size.width}" height="${size.height}">`,
    `<rect width="${size.width}" height="${size.height}" fill="${TILE.fill}"/>`,
    `<rect x="${card.inset}" y="${card.inset}" width="${size.width - 2 * card.inset}" height="${size.height - 2 * card.inset}" rx="${card.radius}" fill="${card.fill}" stroke="${card.stroke}" stroke-width="${card.border}"/>`,
    `<g transform="translate(${tileBox.x},${tileBox.y})">${tile(mark, tileBox)}</g>`,
    highlighterRect(wordmark, highlighter),
    `<g transform="${fitRun(wordmark)}">`,
    `<path fill="${THEMES.dark.ltr}" d="${outlineRun(wordmark.domain, run)}"/>`,
    `<path fill="${THEMES.dark.dot}" d="${outlineRun(wordmark.tld, { ...run, start: wordmark.domain.length })}"/>`,
    '</g>',
    `<g transform="${fitRun(tagline)}"><path fill="${tagline.fill}" d="${outlineRun(tagline.text, tagline)}"/></g>`,
    '</svg>',
  ].join('');
}

/* The highlighter runs under the domain only, never under the `.dev`. */
function highlighterRect(
  { x, baseline, size, advanceEm, domain },
  { fill, opacity, heightEm, dropEm },
) {
  const height = heightEm * size;

  return `<rect x="${x}" y="${baseline + dropEm * size - height}" width="${domain.length * advanceEm * size}" height="${height}" fill="${fill}" fill-opacity="${opacity}"/>`;
}

function frame(svg, size) {
  return new Resvg(svg, { fitTo: { mode: 'width', value: size } })
    .render()
    .asPng();
}

/**
 * Packs the frames into an ICO container: a 6-byte header, one 16-byte
 * entry per frame, then the frames. An entry gives the frame's width,
 * height, color planes, bit depth, byte length, and offset. A frame
 * stays a PNG (ADR 0037).
 */
function ico(frames) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(frames.length, 4);

  let offset = header.length + frames.length * 16;
  const entries = frames.map(({ size, png }) => {
    const entry = Buffer.alloc(16);
    entry.writeUInt8(size, 0);
    entry.writeUInt8(size, 1);
    entry.writeUInt16LE(1, 4);
    entry.writeUInt16LE(32, 6);
    entry.writeUInt32LE(png.length, 8);
    entry.writeUInt32LE(offset, 12);
    offset += png.length;
    return entry;
  });

  return Buffer.concat([header, ...entries, ...frames.map(({ png }) => png)]);
}

function write(name, contents) {
  writeFileSync(new URL(name, PUBLIC_DIR), contents);
  console.log(`wrote public/${name}`);
}
