/* The generator: it writes the brand assets from the mark source
   (ADR 0036). Run it with `npm run generate:icons`. */

import { writeFileSync } from 'node:fs';
import { fitMark, outlineMark } from './mark.mjs';

const PUBLIC_DIR = new URL('../public/', import.meta.url);

const FAVICON = { size: 64, inset: 3 };

const LABEL = 'lf. — lukefredrickson.dev';

/* The favicon sits against the browser tab strip, which follows the OS
   theme and never the site toggle (ADR 0036). */
const THEMES = {
  light: { ltr: '#55516f', dot: '#e1a035' },
  dark: { ltr: '#dddceb', dot: '#ffc05a' },
};

const mark = outlineMark();
write('favicon.svg', faviconSvg(mark));

function faviconSvg({ outlines, ink }) {
  const transform = fitMark(ink, FAVICON);
  const paths = outlines
    .map(({ fillClass, d }) => `<path class="${fillClass}" d="${d}"/>`)
    .join('');
  const { size } = FAVICON;

  return `${[
    '<!-- Generated by `npm run generate:icons`. Do not edit (ADR 0036). -->',
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}" role="img" aria-label="${LABEL}">`,
    `<title>${LABEL}</title>`,
    `<style>${fillRules(THEMES.light)}@media(prefers-color-scheme:dark){${fillRules(THEMES.dark)}}</style>`,
    `<g transform="${transform}">${paths}</g>`,
    '</svg>',
  ].join('\n')}\n`;
}

function fillRules(theme) {
  return Object.entries(theme)
    .map(([fillClass, fill]) => `.${fillClass}{fill:${fill}}`)
    .join('');
}

function write(name, contents) {
  writeFileSync(new URL(name, PUBLIC_DIR), contents);
  console.log(`wrote public/${name}`);
}
